#!/usr/bin/python
#
# Copyright (c) 2012-2013, Arista Networks, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#  - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#  - Neither the name of Arista Networks nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ARISTA NETWORKS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Port auto description
#
#    Version 1.0 8/8/2013
#    Written by: 
#       Mark Berly, Arista Networks
#
#    Revision history:
#       1.0 - initially written using native sysdb calls (deprecated) 
#       2.0 - rewritten using eAPI


"""
   DESCRIPTION
      The port auto description tool automatically updates the port description
      of an interface based on the lldp neighbor information of the attached
      device.

   INSTALLATION
      In order to install portAuto:
      - copy 'portAuto' to /mnt/flash
      - enable eAPI interface
         management api http-commands
            no shutdown
      - change switchIP, username and password to the ones appropriate for your install

      portAuto can then be started using any of the following methods:
          
      1 - Execute directly from bash:
         (bash:root)# /mnt/flash/portAuto &
         
      2 - Configure an alias
         switch2(config)#alias portAuto bash /mnt/flash/portAuto.py
         
      3 - As a scheduled job
          example: In order to run portAuto every 12 hours
      schedule portAuto interval 720 max-log-files 0 command bash sudo /mnt/flash/portAuto

      4 - At boot time, add the following to your configuration:
         event-handler domm
            trigger on-boot
            action bash /mnt/flash/portAuto

   COMPATIBILITY
      Version 2.0 has been developed and tested against EOS-4.12.x and is using 
      the eAPI interface so should maintain backward compatibility with future
      EOS versions.

  LIMITATIONS
      None known
"""

from jsonrpclib import Server
   
def main():
   switchIP = "192.168.3.34"
   userName = "test"
   password = "test"
   switch = Server( "https://%s:%s@%s/command-api" % ( password, userName, switchIP ) )
   response = switch.runCmds( 1, ["show lldp neighbors"] )
   neighborInfo = response[0]["lldpNeighbors"]
   for i in neighborInfo :
      localIntf = i['port']
      intfDesc = "*** Link to " + i['neighborDevice'] + " ( " + i['neighborPort'] + " ) "
      rc = switch.runCmds( 1, ["enable","configure","interface %s" % ( localIntf ),"description %s" % ( intfDesc )])

if __name__ == '__main__':
   main()
