#!/usr/bin/env python 
#
# Copyright (c) 2013, Arista Networks, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#  - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#  - Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#  - Neither the name of Arista Networks nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ARISTA NETWORKS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Port Health Monitor
#
#    Version 1.0 1/10/2013
#    Written by: 
#       Andrei Dvornic, Arista Networks
#
#    Revision history:
#       1.0 - initial release

'''
   DESCRIPTION
      The Port Health Monitor script generates a syslog notification
      whenever the FCS/symbol errors counters on an interface exceed a
      pre-configured level.

   INSTALLATION
      In order to install Port Health Monitor, copy 'phm' to
      /mnt/flash.

      Port Health Monitor can then be started using:
         (bash:root)# /mnt/flash/phm [<options>] &
      and you can use 'nohup' utility in order to make this persistent
      over ssh:
         (bash:root)# nohup /mnt/flash/phm [<options>] &      

      See: 
         (bash:root)# /mnt/flash/phm --help
      for details about the command-line options.

      In order to run Port Health Monitor as a daemon (persistent
      after reboot), add the following to the startup-config:

         event-handler phm
            trigger on-boot
            action bash sudo /usr/bin/daemonize /mnt/flash/phm [<options>] &
            asynchronous
      
      Port Health Monitor process name is 'phm', so standard Linux
      tools can be used to stop and restart it with different options:

      e.g.
         (bash:root)# pkill phm
         (bash:root)# /mnt/flash/phm [<new-options>] &

      Note that in order to make sure the Port Health Monitor does not
      restart on reboot / starts with a different config on reboot,
      the startup-config has to be changed accordingly.

      In order to uninstall Port Health Monitor, use:
         (bash:root)# rm /mnt/flash/phm
         (bash:root)# pkill phm                    // if running

   CONFIGURATION/DEBUGGING
      The default tolerance level for the FCS/symbol errors is 100. In
      order to change that, please use the
      '--fcs--tolerance'/'--symbol-tolerance' command-line options.
      e.g.
         (bash:root)# nohup /mnt/flash/phm -f 500 -s 1000 &

      The base values for the interface error counters are the values
      of the counters when the script is started. Each value is reset
      after each correspoding alert or if the counters are cleared.

      Besides the syslog message, an email alert can also be generated
      when FCS/symbol errors exceed the pre-defined thresholds. To
      enable this feature, configure a destination address using the
      '--email' command-line option:
      e.g.
         (bash:root)# nohup /mnt/flash/phm -e phm@aristanetworks.com

      In order to enable debugging output to stdout, use the '--debug'
      command line option.
      e.g.
         (bash:root)# /mnt/flash/phm -d <email> &
      Note that the output can be quite verbose so it is recommended
      that this option is used with caution, and only for debugging
      purposes.

   COMPATIBILITY
      Version 1.0 has been developed and tested against
      EOS-4.9.7. Please reach out to support@aristanetworks.com if you
      want to run this against a different EOS release.

  LIMITATIONS
      None known.
'''

import optparse
import smtplib
import sys

import Ark
import EntityManager
import Logging
import Tac

from email.mime.text import MIMEText

REPLYTO_ADDR = 'no-reply@example.com' 

# Register as DOM Monitor with LogManager
Ark.configureLogManager( 'phm' )

# Define log messages
INTERFACE_FCS_ERRORS = None
Logging.logD( id='INTERFACE_FCS_ERRORS',
              severity=Logging.logWarning,
              format='FCS errors detected on %s - error count increased '
                     'from %s to %s',
              explanation='FCS error count for interface exceeded threshold',
              recommendedAction=Logging.CALL_SUPPORT_IF_PERSISTS )

INTERFACE_SYMBOL_ERRORS = None
Logging.logD( id='INTERFACE_SYMBOL_ERRORS',
              severity=Logging.logWarning,
              format='Symbol errors detected on %s - error count increased '
                     'from %s to %s',
              explanation='Symbol error count for interface exceeded threshold',
              recommendedAction=Logging.CALL_SUPPORT_IF_PERSISTS )

# Counter base values
errors = {}
errors[ 'fcs' ] = {}
errors[ 'symbol' ] = {}

def mountData():
   # Mount data from Sysdb
   em = EntityManager.Sysdb( 'ar' )
   mg = em.mountGroup()
   allCounter = mg.mount( 'interface/counter/eth/phy',            
                          'Interface::AllEthIntfCounterPtrDir', 'r' )    
   netConfig = mg.mount( 'sys/net/config', 
                         'System::NetConfig', 'r' )
   mg.close( blocking=True )
   return ( allCounter, netConfig )

def _trace( msg ):
   if debug:
      print msg

def _sendEmail( addr, subject, text, sender ):
   msg = MIMEText( text )   
   msg[ 'Subject' ] = subject
   msg[ 'From' ] = sender
   msg[ 'To' ] = addr
   smtp = smtplib.SMTP( 'mx' )
   smtp.sendmail( msg[ 'From' ], addr, msg.as_string() )
   smtp.quit()

def _sendAlarm( hostname, intf, errType, base, newValue, email ):
   _trace( '_sendAlarm( %s, %s, %d, %d )' % 
           ( intf, errType, base, newValue ) )

   if errType.lower() == 'fcs':
      errType = 'FCS'
      Logging.log( INTERFACE_FCS_ERRORS, intf, base, newValue )
   elif errType.lower() == 'symbol':
      errType = 'Symbol'
      Logging.log( INTERFACE_SYMBOL_ERRORS, intf, base, newValue )
   else:
      sys.exit( 'ERROR: unexpected errType in _sendAlarm '
                '(valid values are: fcs, symbol)')

   if not email:
      return

   subject = 'WARNING - Arista Port Health Monitor: ' \
             'port errors detected on %s-%s' % \
             ( hostname, intf )
   
   text = '%s: %s errors on %s increased from %s to %s' % \
          ( hostname, errType, intf, base, newValue  )
   _sendEmail( email, subject, text, REPLYTO_ADDR )

class EthIntfCounterDirReactor( Tac.Notifiee ):
   notifierTypeName = 'Interface::EthIntfCounterDir'

   def __init__( self, notifier, hostname, email, 
                 fcsTolerance, symbolTolerance ):
      _trace( 'EthIntfCounterDirReactor.__init__( %s )' % notifier.name )
      Tac.Notifiee.__init__( self, notifier )

      self.hostname_ = hostname
      self.email_ = email
      self.fcsTolerance_ = fcsTolerance
      self.symbolTolerance_ = symbolTolerance

      self.intfCounterReactor_ = None
      for intfCounter in self.notifier().intfCounter:
         self.handleIntfCounter( intfCounter )

   @Tac.handler( 'intfCounter' )
   def handleIntfCounter( self, key ):
      _trace( 'handleIntfCounter( %s, %s )' % 
              ( self.notifier().name, key ) )

      if key == 'current':
         if key in self.notifier().intfCounter:
            self.intfCounterReactor_ = \
                EthIntfCounterReactor( self.notifier().intfCounter[ key ],
                                       self.hostname_,
                                       self.email_,
                                       self.fcsTolerance_, 
                                       self.symbolTolerance_ )
         else:
            del self.intfCounterReactor_

class EthIntfCounterReactor( Tac.Notifiee ):
   notifierTypeName = 'Interface::EthIntfCounter'

   def __init__( self, notifier, hostname, email, 
                 fcsTolerance, symbolTolerance ):
      Tac.Notifiee.__init__( self, notifier )

      self.hostname = hostname
      self.email_ = email
      self.fcsTolerance_ = fcsTolerance
      self.symbolTolerance_ = symbolTolerance

      self.intf_ = self.notifier().fullName.split( '/' )[ -2 ]
      _trace( 'EthIntfCounterReactor.__init__( %s )' % self.intf_ )

      self.handleEthStatistics()
            
   @Tac.handler( 'ethStatistics' )
   def handleEthStatistics( self ):
      _trace( 'handleEthStatistics( %s )' % self.intf_ )

      if( self.intf_ not in errors[ 'fcs' ] or 
          self.notifier().fcsErrors < errors[ 'fcs' ][ self.intf_ ] ):
         errors[ 'fcs' ][ self.intf_ ] = self.notifier().fcsErrors
      if( self.intf_ not in errors[ 'symbol' ] or 
          self.notifier().symbolErrors < errors[ 'symbol' ][ self.intf_ ] ):
         errors[ 'symbol' ][ self.intf_ ] = self.notifier().symbolErrors

      fcsBase = errors[ 'fcs' ][ self.intf_ ]
      if self.notifier().fcsErrors > ( fcsBase + self.fcsTolerance_ ):
         _sendAlarm( self.hostname, self.intf_, 'fcs', fcsBase,
                     self.notifier().fcsErrors, self.email_ )
         # reset base
         errors[ 'fcs' ][ self.intf_ ] = self.notifier().fcsErrors

      symbolBase = errors[ 'symbol' ][ self.intf_ ]
      if self.notifier().symbolErrors > ( symbolBase + self.symbolTolerance_ ):
         _sendAlarm( self.hostname, self.intf_, 'fcs', symbolBase,
                     self.notifier().symbolErrors, self.email_ )
         # reset base
         errors[ 'symbol' ][ self.intf_ ] = self.notifier().symbolErrors

debug = None
def main():
   global debug

   Tac.setproctitle( 'phm' )

   # Create help string and parse cmd line
   usage = 'usage: %prog [options]'
   op = optparse.OptionParser(usage=usage)
   op.add_option( '-d', '--debug', dest='debug', action='store_true',
                  help='print debug info' )
   op.add_option( '-e', '--email', dest='email', action='store',
                  help='destination email for the alerts' )
   op.add_option( '-f', '--fcs-tolerance', dest='fcsTolerance', action='store',
                  type='int', default=100, 
                  help='increase in FCS errors which triggers '
                       'an alert (default=100)' )
   op.add_option( '-s', '--symbol-tolerance', dest='symbolTolerance', action='store',
                  type='int', default=100, 
                  help='increase in symbol errors which triggers '
                       'an alert (default=100)' )
   opts, args = op.parse_args()
 
   if len( args ):
      op.print_help()
      sys.exit( '\nERROR: Invalid number of arguments' )

   email = opts.email
   debug = opts.debug
   fcsTolerance = opts.fcsTolerance
   symbolTolerance = opts.symbolTolerance

   if fcsTolerance < 1:
      op.error( 'FCS errors tolerance must be a positive number' )
   if symbolTolerance < 1:
      op.error( 'symbol errors tolerance must be a positive number' )

   allCounter, netConfig = mountData()
   _ = Tac.collectionChangeReactor( allCounter.intfCounterDir,
                                    EthIntfCounterDirReactor,
                                    reactorArgs=( netConfig.hostname, email, 
                                    fcsTolerance, symbolTolerance ) )
   
   # Run forever
   Tac.runActivities()

if __name__ == '__main__':
   main()
